name: metabase
services:
  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
    environment:
      - MB_DB_TYPE=postgresql
      - MB_DB_DBNAME=metabase
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase
      - MB_DB_HOST=localhost
      - MB_DB_PORT=5432
    volumes:
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase
      - POSTGRES_DB=metabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

volumes:
  metabase_data:
  postgres_data: