name: airflow-ota

x-airflow-common:
    &airflow-common
    build:
        context: ./.devcontainer
        dockerfile: Dockerfile.airflow
    environment:
        &airflow-common-env
        AIRFLOW_CONFIG: '${AIRFLOW_HOME}/config/airflow.cfg'
        AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_KEY}

        # Core Settings
        AIRFLOW__CORE__EXECUTOR: CeleryExecutor
        AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
        AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
        AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://api-server:8080/execution/'
        AIRFLOW__CORE__AUTH_MANAGER: airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
        
        # Database Settings (Using variables from .env)
        AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}

        # Celery Settings (Using variables from .env)
        AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
        AIRFLOW__CELERY__BROKER_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
        
        # Scheduler Settings
        AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'

        # Webserver Settings (Using variables from .env)
        AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_KEY}
        AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'false'
        AIRFLOW__WEBSERVER__RATELIMIT_STORAGE_URI: "redis://:${REDIS_PASSWORD}@redis:6379/1"

        # Test
        AIRFLOW__WEBSERVER__WEB_SERVER_HOST: 0.0.0.0

        # Optional: Statsd settings for monitoring
        # AIRFLOW__METRICS__STATSD_ON: 'true'
        # AIRFLOW__METRICS__STATSD_HOST: 'statsd-exporter'
        # AIRFLOW__METRICS__STATSD_PORT: '8125'
        # AIRFLOW__METRICS__STATSD_PREFIX: 'airflow'

        # Optional: Add other production configurations like logging, remote task handlers, etc.
        # AIRFLOW__LOGGING__REMOTE_LOGGING: 'true'
        # AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: 's3://my-airflow-logs-bucket/logs'
        # AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: 'aws_default'
        
        HOST_IP: ${HOST_IP:-host.docker.internal}
    volumes:
        - ${AIRFLOW_PROJ_DIR}/dags:${AIRFLOW_HOME}/dags
        - ${AIRFLOW_PROJ_DIR}/config:${AIRFLOW_HOME}/config
        - ${AIRFLOW_PROJ_DIR}/plugins:${AIRFLOW_HOME}/plugins
        - ${AIRFLOW_PROJ_DIR}/logs:${AIRFLOW_HOME}/logs
    user: 
        "${AIRFLOW_UID:-50000}:0"
    env_file:
        - .env
    depends_on:
        &airflow-common-depends-on
        redis:
            condition: service_healthy
        postgres:
            condition: service_healthy
    networks:
        - airflow-network
        - shared-airflow-network
    extra_hosts:
        - "host.docker.internal:host-gateway"

services:
    postgres:
        image: postgres:13
        user: "${POSTGRES_TARGET_UID:-999}:${POSTGRES_TARGET_GID:-999}"
        ports:
            - "${PORT_POSTGRES}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: ${POSTGRES_HOST}
        volumes:
            - postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            retries: 10
            start_period: 5s
        restart: always
        networks:
            - shared-db-network
            - airflow-network

    redis:
        image: redis:7.2-bookworm
        command: 
            ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        expose:
            - 6379
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 10s
            timeout: 10s
            retries: 10
            start_period: 5s
        restart: always
        networks:
            - airflow-network

    api-server:
        <<: *airflow-common
        command: ["api-server"]
        ports:
          - "${PORT_AIRFLOW}:8080"
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 5s
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            init:
                condition: service_completed_successfully

    scheduler:
        <<: *airflow-common
        command: ["scheduler"]
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 30s
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            init:
                condition: service_completed_successfully

    dag-processor:
        <<: *airflow-common
        command: ["dag-processor"]
        healthcheck:
            test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 30s
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            init:
                condition: service_completed_successfully

    worker:
        <<: *airflow-common
        command: ["celery", "worker"]
        healthcheck:
            test:
                - "CMD-SHELL"
                - 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"'
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 30s
        environment:
            <<: *airflow-common-env
            # Required to handle warm shutdown of the celery workers properly
            # See https://airflow.apache.org/docs/docker-stack/entrypoint.html#signal-propagation
            DUMB_INIT_SETSID: "0"
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            api-server:
                condition: service_healthy
            init:
                condition: service_completed_successfully

    triggerer:
        <<: *airflow-common
        command: ["triggerer"]
        healthcheck:
            test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
            interval: 30s
            timeout: 10s
            retries: 10
            start_period: 30s
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            init:
                condition: service_completed_successfully

    init:
        <<: *airflow-common
        entrypoint: /bin/bash
        command:
        - -c
        - |
            if [[ -z "${AIRFLOW_UID}" ]]; then
            echo
            echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
            echo "If you are on Linux, you SHOULD follow the instructions below to set "
            echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
            echo "For other operating systems you can get rid of the warning with manually created .env file:"
            echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
            echo
            fi
            one_meg=1048576
            mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
            cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
            disk_available=$$(df / | tail -1 | awk '{print $$4}')
            warning_resources="false"
            if (( mem_available < 4000 )) ; then
            echo
            echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
            echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
            echo
            warning_resources="true"
            fi
            if (( cpus_available < 2 )); then
            echo
            echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
            echo "At least 2 CPUs recommended. You have $${cpus_available}"
            echo
            warning_resources="true"
            fi
            if (( disk_available < one_meg * 10 )); then
            echo
            echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
            echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
            echo
            warning_resources="true"
            fi
            if [[ $${warning_resources} == "true" ]]; then
            echo
            echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
            echo "Please follow the instructions to increase amount of resources available:"
            echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
            echo
            fi
            mkdir -p ${AIRFLOW_HOME}/{logs,dags,plugins,config}
            chown -R "${AIRFLOW_UID}:0" ${AIRFLOW_HOME}/{logs,dags,plugins,config}
            exec /entrypoint airflow version
        environment:
            <<: *airflow-common-env
            _AIRFLOW_DB_MIGRATE: ${_AIRFLOW_DB_MIGRATE}
            _AIRFLOW_WWW_USER_CREATE: ${_AIRFLOW_WWW_USER_CREATE}
            _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME}
            _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD}
        user: "0:0"
        restart: "no"

    cli:
        <<: *airflow-common
        profiles:
            - debug
        environment:
            <<: *airflow-common-env
            CONNECTION_CHECK_MAX_COUNT: "0"
        tty: true
        stdin_open: true
        depends_on:
            <<: *airflow-common-depends-on

    flower:
        <<: *airflow-common
        command: ["celery", "flower", "--basic-auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]
        profiles:
            - debug
        ports:
            - "${PORT_FLOWER}:5555"
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:5555/"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        restart: always
        depends_on:
            <<: *airflow-common-depends-on
            init:
                condition: service_completed_successfully

# Define internal and external networks
networks:
    airflow-network:
        driver: bridge
        name: airflow-internal-network
    # For Backups and Restores
    shared-db-network:
        driver: bridge
        name: shared-db-network
    shared-airflow-network:
        driver: bridge
        name: shared-airflow-network

# Define named volumes
volumes:
    postgres-db-volume: