name: metabase

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3301:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: metabase-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      retries: 10
      start_period: 5s
    restart: always

volumes:
  metabase_data:
  postgres_data: