version: 3

vars:
  SUDO: '{{if eq OS "linux"}}sudo {{end}}'
  COMPOSE_MB_FILE: compose.metabase.yml
  COMPOSE_AIRFLOW_FILE: compose.airflow.yml
  COMPOSE_DBT_FILE: compose.dbt.yml
  COMPOSE_POSTGRES_FILE: compose.postgres.yml

tasks:
  deploy_metabase:
    description: "Deploy the metabase server"
    cmds:
      - '{{.SUDO}}docker compose -f {{.COMPOSE_MB_FILE}} down'
      - '{{.SUDO}}docker compose -f {{.COMPOSE_MB_FILE}} up -d --build --remove-orphans --force-recreate'

  deploy_airflow:
    description: "Deploy the airflow server"
    cmds:
      - '{{.SUDO}}docker compose -f {{.COMPOSE_AIRFLOW_FILE}} down'
      - '{{.SUDO}}docker compose -f {{.COMPOSE_AIRFLOW_FILE}} up -d --build --remove-orphans --force-recreate'

  deploy_dbt:
    description: "Deploy the dbt server"
    cmds:
      - '{{.SUDO}}docker compose -f {{.COMPOSE_DBT_FILE}} down'
      - '{{.SUDO}}docker compose -f {{.COMPOSE_DBT_FILE}} up -d --build --remove-orphans --force-recreate'

  deploy_postgres:
    description: "Deploy the postgres server"
    cmds:
      - '{{.SUDO}}docker compose -f {{.COMPOSE_POSTGRES_FILE}} down'
      - '{{.SUDO}}docker compose -f {{.COMPOSE_POSTGRES_FILE}} up -d --build --remove-orphans --force-recreate'

  reload_airflow_reqs:
    description: "Update or reload the requirements.txt from pyproject.toml with airflow constraints."
    sources:
      - pyproject.toml
    generates:
      - ./.devcontainer/requirements.txt
    cmds:
      - uv pip compile pyproject.toml -c https://raw.githubusercontent.com/apache/airflow/constraints-3.0.0/constraints-3.12.txt -o ./.devcontainer/requirements.txt
